# Generated by Django 3.1.5 on 2021-02-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criando',
            new_name='criado',
        ),
    ]
